# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PhD
author: Vincent Deguin
logo: OU_logo.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - Thesis_JB/Biblio/Thesis_Bibliography/Chapt1.bib
  - Thesis_JB/Biblio/Thesis_Bibliography/Chapt2.bib
  - Thesis_JB/Biblio/Thesis_Bibliography/Chapt3.bib
  - Thesis_JB/Biblio/Thesis_Bibliography/Chapt4.bib
  - Thesis_JB/Biblio/Thesis_Bibliography/Chapt5.bib
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/Deugz/nb-phd  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)


html:
  favicon                   : "OU_Logo.svg"  
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  use_multitoc_numbering    : false
  extra_navbar              : ""
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : G-EQV9FEH9JF   
  home_page_in_navbar       : true
  baseurl                   : "https://deugz.github.io/nb-phd/_build/html/"
  comments:
    hypothesis              : true
    utterances              : 
      repo: "https://github.com/Deugz/nb-phd"
  announcement              : "Current Version: 09/09/2022"


sphinx:
  config:
    language: en
    html_extra_path: ['Script']
    bibtex_reference_style: author_year
  extra_extensions:
  - sphinx_design